# Generated by Django 4.2 on 2025-09-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Access', '0007_alter_usersession_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenio',
            name='nit',
            field=models.CharField(error_messages={'blank': 'El campo usuario no puede estar vacío.', 'invalid': 'Formato no válido', 'max_length': 'Valor fuera de los límites.', 'unique': 'Este dato ya existe en el sistema. Verifique e intente con uno distinto.'}, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='convenio',
            name='nombre',
            field=models.CharField(error_messages={'blank': 'El campo usuario no puede estar vacío.', 'invalid': 'Formato no válido', 'max_length': 'Valor fuera de los límites.', 'unique': 'Este dato ya existe en el sistema. Verifique e intente con uno distinto.'}, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='convenio',
            name='telefono',
            field=models.CharField(error_messages={'blank': 'El campo usuario no puede estar vacío.', 'invalid': 'Formato no válido', 'max_length': 'Valor fuera de los límites.', 'unique': 'Este dato ya existe en el sistema. Verifique e intente con uno distinto.'}, max_length=10),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='apellidos',
            field=models.CharField(error_messages={'blank': 'El campo usuario no puede estar vacío.', 'invalid': 'Formato no válido', 'max_length': 'Valor fuera de los límites.', 'unique': 'Este dato ya existe en el sistema. Verifique e intente con uno distinto.'}, max_length=60),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cedula',
            field=models.BigIntegerField(error_messages={'blank': 'El campo usuario no puede estar vacío.', 'invalid': 'Formato no válido', 'max_length': 'Valor fuera de los límites.', 'unique': 'Este dato ya existe en el sistema. Verifique e intente con uno distinto.'}, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='correo',
            field=models.EmailField(error_messages={'blank': 'El campo usuario no puede estar vacío.', 'invalid': 'Formato no válido', 'max_length': 'Valor fuera de los límites.', 'unique': 'Este dato ya existe en el sistema. Verifique e intente con uno distinto.'}, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombres',
            field=models.CharField(error_messages={'blank': 'El campo usuario no puede estar vacío.', 'invalid': 'Formato no válido', 'max_length': 'Valor fuera de los límites.', 'unique': 'Este dato ya existe en el sistema. Verifique e intente con uno distinto.'}, max_length=60),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='ciudad',
            field=models.CharField(error_messages={'blank': 'El campo usuario no puede estar vacío.', 'invalid': 'Formato no válido', 'max_length': 'Valor fuera de los límites.', 'unique': 'Este dato ya existe en el sistema. Verifique e intente con uno distinto.'}, max_length=50),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='direccion',
            field=models.CharField(error_messages={'blank': 'El campo usuario no puede estar vacío.', 'invalid': 'Formato no válido', 'max_length': 'Valor fuera de los límites.', 'unique': 'Este dato ya existe en el sistema. Verifique e intente con uno distinto.'}, max_length=50),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='nombre',
            field=models.CharField(error_messages={'blank': 'El campo usuario no puede estar vacío.', 'invalid': 'Formato no válido', 'max_length': 'Valor fuera de los límites.', 'unique': 'Este dato ya existe en el sistema. Verifique e intente con uno distinto.'}, max_length=50),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='telefono',
            field=models.CharField(error_messages={'blank': 'El campo usuario no puede estar vacío.', 'invalid': 'Formato no válido', 'max_length': 'Valor fuera de los límites.', 'unique': 'Este dato ya existe en el sistema. Verifique e intente con uno distinto.'}, max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
